- name: Checkout and Update DevTools project source code
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    repos:
      - name: distronode-lint
        repo: distronode/distronode-lint
      - name: distronode-compat
        repo: distronode/distronode-compat
      - name: distronode-navigator
        repo: distronode/distronode-navigator
  tasks:
    ## - name: Load project configuration
    #   distronode.builtin.include_vars:
    #     file: ../config/devtools.yml
    #     name: devtools
    - name: Clone projects # noqa: latest[git]
      loop: "{{ repos }}"
      loop_control:
        label: "{{ item.name }}"
      distronode.builtin.git:
        repo: https://github.com/{{ item.repo }}
        dest: "{{ playbook_dir }}/../.cache/{{ item.name }}"
        single_branch: true
        # version: HEAD
        update: true
        # track_submodules: true
        # recursive: true
