name: notify
on:
  discussion:
    types: [created, transferred]
  workflow_call:
    # https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#onworkflow_callinputs
    inputs:
      message:
        description: Message to be posted
        type: string
        default: Hello!
      matrix_room_id:
        description: Matrix ROOM ID
        type: string
        default: "!aqMMMrOxRZzVDkUlWF:matrix.org" # distronode-devtools
  workflow_dispatch:
    inputs:
      message:
        description: Message to be posted
        type: string
        default: Hello!
      matrix_room_id:
        description: Matrix ROOM ID
        type: string
        default: "!aqMMMrOxRZzVDkUlWF:matrix.org" # distronode-devtools

jobs:
  send-message:
    runs-on: ubuntu-latest
    if: ${{ github.event.action == 'created' }}
    name: Send message via Matrix
    environment: notify
    steps:
      # - name: Send message to test channel
      #   id: matrix-chat-message
      #   uses: fadenb/matrix-chat-message@v0.0.6
      #   with:
      #     homeserver: 'matrix.org'
      #     token: ${{ secrets.MATRIX_TOKEN }}
      #     channel: ${{ inputs.matrix_room_id }}
      #     message: ${{ inputs.message }}

      - name: send message
        uses: s3krit/matrix-message-action@v0.0.3
        with:
          room_id: "!aqMMMrOxRZzVDkUlWF:matrix.org" # distronode-devtools
          access_token: ${{ secrets.MATRIX_TOKEN }}
          # https://doc.matrix.tu-dresden.de/en/messaging/formatting/
          message: >
            💬 [${{ github.event.discussion.title }}](${{ github.event.discussion.html_url }})
            was posted in _${{ github.event.discussion.category.slug }}_
            by [${{ github.event.discussion.user.login }}](${{ github.event.discussion.user.html_url }})
          server: matrix.org
