---
name: Galaxy Release
on:
  workflow_call:
    inputs:
      environment:
        description: The deployment environment
        required: true
        type: string
      galaxy_publish:
        default: true
        description: Publish the collection on galaxy
        type: boolean
    secrets:
      distronode_galaxy_api_key:
        required: false

jobs:
  release:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v4

      - name: "Build the collection"
        run: |
          distronode-galaxy collection build -v --force

      - name: "Publish the collection on Galaxy"
        if: ${{ inputs.galaxy_publish }}
        run: |
          [[ "${{ secrets.distronode_galaxy_api_key != '' }}" ]] || { echo "distronode_galaxy_api_key is required to publish on galaxy" ; exit 1; }
          TARBALL=$(ls -1 ./*.tar.gz)
          distronode-galaxy collection publish "${TARBALL}" --api-key "${{ secrets.distronode_galaxy_api_key }}"
